### ISSUE TITLE
Consider adding an extra folder for output?

### ISSUE THREAD

**Issue by m3hr** [mwhite/resume#30]
I use `resume` and keep a folder within the repo called `my_stuff` where I copy-paste my `make` output and maintain a separate git repo. It would be more modular and make more sense if this were the default, in my opinion. Output and code are probably best kept in separate folders, I think. Thoughts?

**Comment by mwhite** [comment]
I appreciate the thought, and you are right that it would be better to have a build folder for the .pdf and .html, but I'm going to keep it the way it is because:

- I keep mine separate by having a different branch with a different filename for my resumé.  That's arguably the right solution in terms of versioning, certainly adequate.
- The Makefile got made all fancy by someone else, and I don't know how to change it to put the pdf and html in a separate directory from the markdown, and don't really care to look into it, since it works now.  Feel free to submit a PR.
